name: "GitHub Yak Action"
description: 'A Github Action that checks your repository for certains files'
author: jonasbn
inputs:
  yak-arguments:  # id of input
    description: 'Arguments for yak'
    required: false
branding:
  color: green
  icon: type
runs:
  using: docker
  image: 'docker://jonasbn/yak:latest'
  args:
    - ${{ inputs.yak-arguments }}
